"""added table KanbanBoard

Revision ID: 6d21947ea7e1
Revises: 72bae2df2492
Create Date: 2023-12-13 20:34:46.204690

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d21947ea7e1"
down_revision: Union[str, None] = "72bae2df2492"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kanban_board",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("xml", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kanban_board")
    # ### end Alembic commands ###
